### ISSUE TITLE
The AddTable does not need to take in an additional err parameter

### ISSUE THREAD

**Issue by hosaka** [dextor19/downtable#2]
I am guessing this was added to be able to make calls like (only in tests, not used in the lib internally):
```golang
mdt.AddTable(WithCSVFile(...))
```
The error should be checked outside of the implementation, before calling the `AddTable`.

**Comment by dextor19** [comment]
As discussed in #4  I will reimplement this `WithCSVFile` to be like `MarkdownTable.AddJSONFileTable()`

**Comment by dextor19** [comment]
resolve in #4
